### ISSUE TITLE
Cordova/Phonegap splash screens support

### ISSUE THREAD

**Issue by trendchaser4u** [quasarframework/quasar-icon-factory#11]
In addition with icon generation provide hybrid app splash screen support.

**Comment by nothingismagick** [comment]
Great!

**Comment by trendchaser4u** [comment]
Hi @nothingismagick ,

Here I attached configuration objects for splash screen :) as we discussed

[splash.js.zip](https://github.com/nothingismagick/icon-factory/files/2020272/splash.js.zip)

**Comment by nothingismagick** [comment]
As far as ios goes, this is what the cordova docs say:
```
     <!-- Storyboard method (supports all devices):
       -- Important: If you use the storyboard method, legacy images are 
       -- copied but ignored.
       -- Note: images are determined by scale, idiom, and size traits. The following
       -- are suggested based on current device form factors -->
    <splash src="res/screen/ios/Default@2x~universal~anyany.png" />
    <splash src="res/screen/ios/Default@2x~universal~comany.png" />
    <splash src="res/screen/ios/Default@2x~universal~comcom.png" />
    <splash src="res/screen/ios/Default@3x~universal~anyany.png" />
    <splash src="res/screen/ios/Default@3x~universal~anycom.png" />
```

**Comment by nothingismagick** [comment]
And on a sidenote, I have seen that there are issues with cached splashscreens not changing unless you delete the app.

Maybe its a good idea to always use a cachebusting route like 
src="Default@3x~universal~anycom.png?t=${timestamp}"

I have no idea if that would work though.

**Comment by nothingismagick** [comment]
Once I have your iOS icons I will close this issue.

**Comment by nothingismagick** [comment]
@trendchaser4u - have you had any time to look at this?
