### ISSUE TITLE
npm repo Not found

### ISSUE THREAD

**Issue by plopApy** [quasarframework/quasar-icon-factory#14]
Good morning,
Cannot install quasar-icon-factory with the following methods :

```
$ yarn global add quasar-icon-factory 
- or -
$ npm install --global quasar-icon-factory 
```

Here is the answer to the command:
`error An unexpected error occurred: "https://registry.yarnpkg.com/quasar-icon-factory: Not found".`

**Comment by rstoenescu** [comment]
Hi, it hasn't been published to NPM yet.
